# -*- coding: utf-8 -*-
"""student_performance_analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ceD9wuqGL_9uvvfYT81b1SeTKNbzDxPO
"""

pip install pandas matplotlib seaborn

# ==========================================
# STUDENT PERFORMANCE ANALYTICS PROJECT
# ==========================================

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Create folders

os.makedirs("charts", exist_ok=True)
os.makedirs("output", exist_ok=True)

# Load Dataset

df = pd.read_csv("StudentsPerformance.csv")

# Dataset Information

print("\n===== DATASET INFO =====\n")
print(df.info())

print("\n===== FIRST 5 ROWS =====\n")
print(df.head())

# Save cleaned dataset

df.to_csv("output/cleaned_student_data.csv", index=False)

# ==========================================
# 1. GENDER DISTRIBUTION
# ==========================================

plt.figure(figsize=(6,4))

sns.countplot(x='gender', data=df)

plt.title("Student Gender Distribution")

plt.savefig("charts/gender_distribution.png")

plt.show()

# ==========================================
# 2. MATH SCORE DISTRIBUTION
# ==========================================

plt.figure(figsize=(8,5))

sns.histplot(df['math score'], bins=20, kde=True)

plt.title("Math Score Distribution")

plt.savefig("charts/math_score_distribution.png")

plt.show()

# ==========================================
# 3. READING SCORE DISTRIBUTION
# ==========================================

plt.figure(figsize=(8,5))

sns.histplot(df['reading score'], bins=20, kde=True)

plt.title("Reading Score Distribution")

plt.savefig("charts/reading_score_distribution.png")

plt.show()

# ==========================================
# 4. WRITING SCORE DISTRIBUTION
# ==========================================

plt.figure(figsize=(8,5))

sns.histplot(df['writing score'], bins=20, kde=True)

plt.title("Writing Score Distribution")

plt.savefig("charts/writing_score_distribution.png")

plt.show()

# ==========================================
# 5. PARENTAL EDUCATION ANALYSIS
# ==========================================

plt.figure(figsize=(12,6))

sns.boxplot(
    x='parental level of education',
    y='math score',
    data=df
)

plt.xticks(rotation=45)

plt.title("Parental Education vs Math Score")

plt.savefig("charts/parental_education_analysis.png")

plt.show()

# ==========================================
# 6. TEST PREPARATION ANALYSIS
# ==========================================

plt.figure(figsize=(8,5))

sns.boxplot(
    x='test preparation course',
    y='math score',
    data=df
)

plt.title("Test Preparation vs Math Score")

plt.savefig("charts/test_preparation_analysis.png")

plt.show()

# ==========================================
# 7. SCORE CORRELATION
# ==========================================

scores = df[['math score',
             'reading score',
             'writing score']]

plt.figure(figsize=(8,6))

sns.heatmap(
    scores.corr(),
    annot=True
)

plt.title("Score Correlation Matrix")

plt.savefig("charts/score_correlation.png")

plt.show()

# ==========================================
# BUSINESS INSIGHTS
# ==========================================

print("\n===== ANALYTICS INSIGHTS =====\n")

print("1. Compare student performance across subjects.")
print("2. Study parental education impact.")
print("3. Analyze benefits of test preparation.")
print("4. Understand score relationships.")
print("5. Identify performance trends.")

print("\nPROJECT COMPLETED SUCCESSFULLY!")